# Describes the format for available LCN services

led:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    led:
      required: true
      default: "led1"
      selector:
        select:
          options:
            - "led1"
            - "led2"
            - "led3"
            - "led4"
            - "led5"
            - "led6"
            - "led7"
            - "led8"
            - "led9"
            - "led10"
            - "led11"
            - "led12"
    led_state:
      required: true
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
            - "blink"
            - "flicker"

var_abs:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    variable:
      required: true
      selector:
        select:
          options:
            - "r1var"
            - "r2var"
            - "r1varsetpoint"
            - "r2varsetpoint"
            - "tvar"
            - "var1ortvar"
            - "var2orr1var"
            - "var3orr2var"
            - "var1"
            - "var2"
            - "var3"
            - "var4"
            - "var5"
            - "var6"
            - "var7"
            - "var8"
            - "var9"
            - "var10"
            - "var11"
            - "var12"
    value:
      required: true
      default: 0
      selector:
        number:
          min: 0
          max: 100000
    unit_of_measurement:
      selector:
        select:
          options:
            - "%"
            - "°"
            - "°C"
            - "°F"
            - "ampere"
            - "amp"
            - "a"
            - "degree"
            - "native"
            - "k"
            - "lcn"
            - "lux_t"
            - "lx_t"
            - "lux_i"
            - "lux"
            - "lx"
            - "m/s"
            - "meterpersecond"
            - "percent"
            - "ppm"
            - "v"
            - "volt"

var_reset:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    variable:
      required: true
      selector:
        select:
          options:
            - "r1var"
            - "r2var"
            - "r1varsetpoint"
            - "r2varsetpoint"
            - "tvar"
            - "var1ortvar"
            - "var2orr1var"
            - "var3orr2var"
            - "var1"
            - "var2"
            - "var3"
            - "var4"
            - "var5"
            - "var6"
            - "var7"
            - "var8"
            - "var9"
            - "var10"
            - "var11"
            - "var12"

var_rel:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    variable:
      required: true
      selector:
        select:
          options:
            - "r1var"
            - "r2var"
            - "r1varsetpoint"
            - "r2varsetpoint"
            - "thrs1"
            - "thrs2"
            - "thrs3"
            - "thrs4"
            - "thrs5"
            - "thrs2_1"
            - "thrs2_2"
            - "thrs2_3"
            - "thrs2_4"
            - "thrs3_1"
            - "thrs3_2"
            - "thrs3_3"
            - "thrs3_4"
            - "thrs4_1"
            - "thrs4_2"
            - "thrs4_3"
            - "thrs4_4"
            - "tvar"
            - "var1ortvar"
            - "var2orr1var"
            - "var3orr2var"
            - "var1"
            - "var2"
            - "var3"
            - "var4"
            - "var5"
            - "var6"
            - "var7"
            - "var8"
            - "var9"
            - "var10"
            - "var11"
            - "var12"
    value:
      required: true
      default: 0
      selector:
        number:
          min: 0
          max: 100000
    unit_of_measurement:
      selector:
        select:
          options:
            - "%"
            - "°"
            - "°C"
            - "°F"
            - "ampere"
            - "amp"
            - "a"
            - "degree"
            - "native"
            - "k"
            - "lcn"
            - "lux_t"
            - "lx_t"
            - "lux_i"
            - "lux"
            - "lx"
            - "m/s"
            - "meterpersecond"
            - "percent"
            - "ppm"
            - "v"
            - "volt"
    value_reference:
      selector:
        select:
          options:
            - "current"
            - "prog"

lock_regulator:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    setpoint:
      required: true
      default: "thrs1"
      selector:
        select:
          options:
            - "thrs1"
            - "thrs2"
            - "thrs3"
            - "thrs4"
            - "thrs5"
            - "thrs2_1"
            - "thrs2_2"
            - "thrs2_3"
            - "thrs2_4"
            - "thrs3_1"
            - "thrs3_2"
            - "thrs3_3"
            - "thrs3_4"
            - "thrs4_1"
            - "thrs4_2"
            - "thrs4_3"
            - "thrs4_4"
    lock_state:
      required: true
      selector:
        boolean:

send_key:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    key:
      required: true
      default: "a1"
      example: "a5"
      selector:
        select:
          options:
            - "a1"
            - "a2"
            - "a3"
            - "a4"
            - "a5"
            - "a6"
            - "a7"
            - "a8"
            - "b1"
            - "b2"
            - "b3"
            - "b4"
            - "b5"
            - "b6"
            - "b7"
            - "b8"
            - "c1"
            - "c2"
            - "c3"
            - "c4"
            - "c5"
            - "c6"
            - "c7"
            - "c8"
            - "d1"
            - "d2"
            - "d3"
            - "d4"
            - "d5"
            - "d6"
            - "d7"
            - "d8"
    key_state:
      required: true
      default: "hit"
      selector:
        select:
          translation_key: "key_state"
          options:
            - "hit"
            - "make"
            - "break"
    time:
      selector:
        number:
          min: 0
          max: 60
    time_unit:
      selector:
        select:
          options:
            - "days"
            - "hours"
            - "minutes"
            - "seconds"

lock_key:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    key:
      required: true
      default: "a1"
      example: "a5"
      selector:
        select:
          options:
            - "a1"
            - "a2"
            - "a3"
            - "a4"
            - "a5"
            - "a6"
            - "a7"
            - "a8"
            - "b1"
            - "b2"
            - "b3"
            - "b4"
            - "b5"
            - "b6"
            - "b7"
            - "b8"
            - "c1"
            - "c2"
            - "c3"
            - "c4"
            - "c5"
            - "c6"
            - "c7"
            - "c8"
            - "d1"
            - "d2"
            - "d3"
            - "d4"
            - "d5"
            - "d6"
            - "d7"
            - "d8"
    lock_state:
      required: true
      default: "on"
      selector:
        select:
          translation_key: "lock_state"
          options:
            - "on"
            - "off"
            - "toggle"
    time:
      selector:
        number:
          min: 0
          max: 60
    time_unit:
      selector:
        select:
          options:
            - "days"
            - "hours"
            - "minutes"
            - "seconds"

dyn_text:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    row:
      required: true
      default: 1
      selector:
        number:
          mode: "box"
          min: 1
          max: 4
    text:
      required: true
      example: "text up to 60 characters"
      selector:
        text:

pck:
  fields:
    device_id:
      required: true
      example: "91aa039a2fb6e0b9f9ec7eb219a6b7d2"
      selector:
        text:
    pck:
      required: true
      example: "PIN4"
      selector:
        text:
